### ISSUE TITLE
Combine models

### ISSUE THREAD

**Issue by tankz0r** [neptune-ml/open-solution-home-credit#135]
Hi, I see that you have 5 different models or so: xgboost, lightgbm, RF, LR, SVM. 
Why do you not use the combinations of results of these models: average mean or some other weight combination?

**Comment by jakubczakon** [comment]
@tankz0r we want to build a solid feature space first.

That being said this week we will start adding diversity and since we have already implemented stacking infrastructure. It is super easy to add second level model to do the *weighing*.

Thanks for noticing it though. It is a great point and I think it is extremely difficult to do well without it.
