### ISSUE TITLE
CV improved LB not

### ISSUE THREAD

**Issue by davutpolat** [neptune-ml/open-solution-home-credit#195]
Hi guys, 

i have extracted  some more features  from bureau file, it improved CV 
from .7950 to  0.7974 ( std 0.0024)  but  LB drop from .804 to .802.   has anyone  experienced this before ? 
i dont use any TARGET related  features, and dont think it is overfitting.

**Comment by jakubczakon** [comment]
Hi there @davutpolat. Good job on improving the score so much.

The diff between CV and LB with this particular public LB (that is super tiny) could definitely be due to luck alone.
We will submit best local CV and best LB for our two submissions and I don't know if you can do more about it unfortunatelly.

Best and good luck!
